### PR TITLE
Make bundled extension branch selectable

### LINKED ISSUE #388: branch ignored when building a bundled extension
## Linux distribution and version

Fedora 33

## Flatpak-builder version

flatpak-builder 1.0.12

## Flatpak version

Flatpak 1.10.2

## Description of the problem

I'm trying to build a bundled extension from an application. It happens that this extension is a set of audio plugins that can be used by other applications.
I set the `branch` property to `20.08` and it is ignored when generating the extension bundle.
See the manifest https://github.com/flathub/org.guitarix.Guitarix/blob/7571ee0e8dc08f698ed831c08bc083920dd3876c/org.guitarix.Guitarix.json

## Steps to reproduce

- Build https://github.com/flathub/org.guitarix.Guitarix
- The resulting bundled extension `org.freedesktop.LinuxAudio.Plugins.Guitarix` doesn't have the branch `20.08`.

Current result is:
```
$ flatpak install guitarix-origin Guitarix
Looking for matches…
Similar refs found for ‘Guitarix’ in remote ‘guitarix-origin’ (user):

   1) app/org.guitarix.Guitarix/x86_64/master
   2) runtime/org.freedesktop.LinuxAudio.Plugins.Guitarix/x86_64/master

Which do you want to use (0 to abort)? [0-2]: 
```

### PR DESCRIPTION
**Pull request by gasinvein**
When `add-extension` entry with `bundle: true` explicitly specifies `version`, export the extension under this branch, instead of always using parent app branch.
Fixes #388

### CODE REVIEW

File: src/builder-main.c [hunk 1]
```diff
@@ -1097,9 +1097,13 @@ main (int    argc,
                                        builder_context_get_build_runtime (build_context) ? "usr" : "files",
                                        builder_extension_get_directory (e));
 
+          const char *externsion_branch = builder_extension_get_version(e);
```
Comment (hfiguiere) [inline src/builder-main.c:1100]: did you really mean `externsion` ?

Comment (gasinvein) [reply src/builder-main.c]: No, it's a typo.

File: src/builder-main.c [hunk 2]
```diff
@@ -1097,9 +1097,13 @@ main (int    argc,
                                        builder_context_get_build_runtime (build_context) ? "usr" : "files",
                                        builder_extension_get_directory (e));
 
+          const char *extension_branch = builder_extension_get_version(e);
```
Comment (mwleeds) [inline src/builder-main.c:1100]: need a space before the left parenthesis

File: src/builder-main.c [hunk 3]
```diff
@@ -1097,9 +1097,13 @@ main (int    argc,
...
+          if (extension_branch == NULL)
+            extension_branch = builder_manifest_get_branch (manifest, build_context);
+
           if (!do_export (build_context, &error, TRUE,
                           flatpak_file_get_path_cached (export_repo),
-                          app_dir_path, NULL, builder_manifest_get_branch (manifest, build_context),
+                          app_dir_path, NULL, extension_branch,
```
Comment (mwleeds) [inline src/builder-main.c:1106]: Do we need a similar change in `builder_manifest_finish()` since that also iterates over the non-bundled extensions and writes metadata for them? Have you checked if this patch works for fixing #388?

Comment (gasinvein) [reply src/builder-main.c:1106]: >Do we need a similar change in `builder_manifest_finish()` since that also iterates over the non-bundled extensions and writes metadata for them?

No, unless I'm missing something, `builder_manifest_finish()` doesn't write the extension branch anywhere.

>Have you checked if this patch works for fixing #388?

Yes, although for another case. It seems to do the trick.

Comment (mwleeds) [reply src/builder-main.c:1106]: > > Do we need a similar change in `builder_manifest_finish()` since that also iterates over the non-bundled extensions and writes metadata for them?
> 
> No, unless I'm missing something, `builder_manifest_finish()` doesn't write the extension branch anywhere.

Yeah, I see now that the `version` key can be defined for `[Extension NAME]` sections according to `flatpak-metadata(5)` but not `[Runtime]` as is being written in this case. So I guess you're right, it's not needed.

**Comment by mwleeds** [comment]
Presumably not the fault of this patch but the CI is failing:
```
Run sudo add-apt-repository ppa:alexlarsson/flatpak
  Linux application sandboxing and distribution framework
 More info: https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4003 B]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2070 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [414 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1735 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [369 kB]
Get:10 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic InRelease [21.3 kB]
Get:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [188 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1727 kB]
Hit:13 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:14 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Get:15 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [322 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1127 kB]
Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [254 kB]
Get:18 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic/main amd64 Packages [4436 B]
Get:19 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic/main Translation-en [3080 B]
Fetched 8490 kB in 2s (4673 kB/s)
Reading package lists...
 
 More info: https://launchpad.net/~alexlarsson/+archive/ubuntu/glib260
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:6 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic InRelease
Get:7 http://ppa.launchpad.net/alexlarsson/glib260/ubuntu bionic InRelease [15.9 kB]
Hit:8 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Get:10 http://ppa.launchpad.net/alexlarsson/glib260/ubuntu bionic/main amd64 Packages [2012 B]
Get:11 http://ppa.launchpad.net/alexlarsson/glib260/ubuntu bionic/main Translation-en [1100 B]
Fetched 19.0 kB in 2s (10.6 kB/s)
Reading package lists...
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:6 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/alexlarsson/glib260/ubuntu bionic InRelease
Hit:8 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
automake is already the newest version (1:1.15.1-3ubuntu2).
automake set to manually installed.
bison is already the newest version (2:3.0.4.dfsg-1build1).
shared-mime-info is already the newest version (1.9-2).
shared-mime-info set to manually installed.
dbus is already the newest version (1.12.2-1ubuntu1.2).
patch is already the newest version (2.7.6-2ubuntu1.1).
unzip is already the newest version (6.0-21ubuntu1.1).
libglib2.0-cil is already the newest version (2.12.45-0xamarin19+ubuntu1804b1).
libglib2.0-cil set to manually installed.
git is already the newest version (1:2.31.1-0ppa1~ubuntu18.04.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-cil-dev : Depends: libglib2.0-cil (= 2.12.40-2) but 2.12.45-0xamarin19+ubuntu1804b1 is to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

**Comment by gasinvein** [comment]
@mwleeds Flatpak CI faced presumably the same issue and was fixed by  flatpak/flatpak@b6d5e20857b3587c212ce97de78cdbc2ef01d548, maybe the same should be done for flatpak-builder?

**Comment by mwleeds** [comment]
> @mwleeds Flatpak CI faced presumably the same issue and was fixed by [flatpak/flatpak@b6d5e20](https://github.com/flatpak/flatpak/commit/b6d5e20857b3587c212ce97de78cdbc2ef01d548), maybe the same should be done for flatpak-builder?

Thanks, opened #392 for that

**Comment by mwleeds** [comment]
Force-pushed to rebase this on master
